version: '3.8'

volumes:
  postgres_data:

networks:
  backend:


services:
  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: ${NODE_ENV}
    env_file:
      - .env
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    networks:
      - backend
