version: '3.8'

volumes:
  postgres_data:

networks:
  backend:
  frontend:

services:
  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  nest:
    build:
      context: ./backend
      target: ${NODE_ENV}
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    networks:
      - backend
  vite:
    build:
      context: ./vite
      target: ${NODE_ENV}
    env_file:
      - .env
    restart: always
    volumes:
      - ./vite:/www/vite/
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      target: ${NODE_ENV}
    restart: always
    ports:
      - 4243:4243
    depends_on:
      - vite
    volumes:
      #- ./nginx/dev_nginx.conf:/etc/nginx/nginx.conf
      - ./vite/dist:/www/vite/dist
    networks:
      - backend
