version: '3.8'

volumes:
  postgres_data:

networks:
  backend:


services:
  postgres:
    image: postgres
    env_file:
      - ./docker/postgres/.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
