version: '3.8'

volumes:
  postgres_data:

networks:
  backend:


services:
  postgres:
    image: postgres
    env_file:
      - ./docker/postgres/.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - ./docker/backend/.env
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    networks:
      - backend
