version: '3.8'

volumes:
  postgres_data:

networks:
  backend:
  frontend:

services:
  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  nest:
    build:
      context: ./backend
      target: ${NODE_ENV}
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - ./nginx/avatars:/usr/src/app/avatars
    networks:
      - backend
    ports:
      - 3000:3000
  vite:
    build:
      context: ./vite
    env_file:
      - .env
    restart: on-failure #A changer en prod
    volumes:
      - ./vite:/www/vite/
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./vite/dist:/www/vite/dist
      - ./nginx/avatars:/www/avatars
    networks:
      - backend

  # pgadmin:
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   networks:
  #     - backend
  #   ports:
  #     - 5050:80
  #   restart: always
