###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM nginx:1.17.6-alpine as development
COPY dev_nginx.conf /etc/nginx/nginx.conf

###################
# BUILD FOR PRODUCTION
###################

FROM nginx:1.17.6-alpine as build
COPY prod_nginx.conf /etc/nginx/nginx.conf